### ISSUE TITLE
fix failing tests

### ISSUE THREAD

**Issue by sinisterstuf** [bblimke/webmock#503] opened 2015-08-20 23:10 UTC
It is difficult to see whether the project is stable and whether pull requests should be merged because currently the tests fail. Turning off sudo with PR #499 was a simple way to get a lot of them running. I had a look at the rest but unfortunately they aren't as simple and I don't know Ruby well enough. One problem seems to be that the status responses are now not just numbers, i.e. `200 OK` instead of `200`. Issue #494 is possibly related.

**Comment by presidentJFK** [comment] 2015-08-29 23:55
Thanks for submitting an issue, however I am going to close this as a duplicate of #494.

We are working on this though. I just opened PR #507 built off of @mikeknep PR #506 attempting to fix this issue. We now just need to do some more research into why are all the failures are happening exactly and what's the optimal solution.

So hopefully this won't be an issue anymore soon, but If you have any extra time, any help would be greatly appreciated!

**Closed by presidentJFK** 2015-08-29 23:55 UTC
