### ISSUE TITLE
Raise then return does not seem to be working?

### ISSUE THREAD

**Issue by clarkbremer** [bblimke/webmock#423] opened 2014-10-23 13:41 UTC
I'm trying to test some code that recovers from an API failing temporarily.  My code looks like this:

```
 stub_request(:post, /^#{my_urll}/).
    to_raise.then.
    to_return(status: 200, body: '{}')
```

But is seems to raise every time, and not ever return the 200 status.  Does the `raise` somehow mess up the state that keeps track of which request we are on?

**Comment by presidentJFK** [comment] 2015-05-10 02:28
Closing this since it is not reproducible. Thanks for submitting the issue, and if you see it again and can reproduce the bug in a test, please reopen this issue.

**Closed by presidentJFK** 2015-05-10 02:28 UTC
