### ISSUE TITLE
VersionChecker Logic is giving false negatives.

### ISSUE THREAD

**Issue by dvantuyl** [bblimke/webmock#1022] opened 2023-04-06 01:16 UTC
**Error:**
```sh
You are using Curb 0.9.10. WebMock is known to work with Curb >= 0.7.16, < 1.1, except versions 0.8.7. It may not work with this version.
```

**[Broken Code (github link):](https://github.com/bblimke/webmock/blob/ab85203aab16ac9ac975719b12a2608151bcce89/lib/webmock/util/version_checker.rb#L90)**
```ruby
    def compare_version
      case
        when @major < @min_major then :too_low
        when @max_major && @major > @max_major then :too_high
        when @major > @min_major then :ok
        when @minor < @min_minor then :too_low
        when @max_minor && @minor > @max_minor then :too_high
        when @minor > @min_minor then :ok
        when @patch < @min_patch then :too_low
      end
    end
```

**Values Mapped:**
```
@major = 0
@minor = 9
@patch = 10

@min_major = 0
@min_minor = 7
@min_patch = 16

@max_major = 1
@max_minor = 0
@max_patch = 1
```

**Issue:**
1. Passes through first `:ok` since (0 > 0) == false
2. Errors on the second `:too_high` since (1 && 9 > 0)

**Comment by knarewski** [comment] 2023-04-06 13:31
Likely a duplicate of https://github.com/bblimke/webmock/pull/1006 ?

**Comment by dvantuyl** [comment] 2023-04-06 16:13
Yes thank you @knarewski. Closing as duplicate.

**Closed** 2023-04-06 16:13 UTC
